vtune: Warning: Only user space will be profiled due to credentials lack. Consider changing /proc/sys/kernel/perf_event_paranoid file for enabling kernel space profiling.
vtune: Collection started. To stop the collection, either press CTRL-C or enter from another console window: vtune -r /work/apac4/xbx/apac/hpc/hoomd-benchmarks/r001hs -command stop.
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
mpirun: Forwarding signal 18 to job
Traceback (most recent call last):
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/work/apac4/xbx/apac/hpc/hoomd-benchmarks/hoomd_benchmarks/md_pair_wca.py", line 6, in <module>
    import hoomd
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/__init__.py", line 60, in <module>
    from hoomd import version
  File "/work/apac4/miniforge3/envs/apac-hpc-xbx/lib/python3.10/site-packages/hoomd/version.py", line 64, in <module>
    from hoomd import _hoomd
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
Terminated
